### ISSUE TITLE
登录提示500

### ISSUE THREAD

**Issue by Ghost-Cavendish** [openBI-kwc/openBI#1]
![image](https://user-images.githubusercontent.com/56330712/109779710-2cb96c80-7c41-11eb-9039-aad084b93847.png)
宝塔一键部署的

**Comment by myrust-go** [comment]
求助，更新一下吧

**Comment by lty628** [comment]
> ![image](https://user-images.githubusercontent.com/56330712/109779710-2cb96c80-7c41-11eb-9039-aad084b93847.png)
> 宝塔一键部署的

问题已修复，修复后请安装版本 v1.0.1

**Comment by chjw8016** [comment]
安装v1.0.1，还是提示登录失败，500错误。
![image](https://user-images.githubusercontent.com/7558748/110408393-69adb500-80c0-11eb-88e4-24bf26967669.png)
![image](https://user-images.githubusercontent.com/7558748/110408411-73cfb380-80c0-11eb-9883-9b30525f9580.png)

**Comment by lty628** [comment]
建议采用nginx服务器，apache之后我们测试下

**Comment by QQ1044** [comment]
同样问题，禁用putenv()函数后可以正常登录

**Comment by QQ1044** [comment]
![image](https://user-images.githubusercontent.com/54705555/110564242-78ab6a80-8187-11eb-9689-5085d1092dfe.png)
修改密码出现了错误

**Comment by fulongli** [comment]
https://github.com/openBI-kwc/openBI/commit/42b55c087e07cc1fc98a9f7f40e3b4e14806b5e1

> ![image](https://user-images.githubusercontent.com/54705555/110564242-78ab6a80-8187-11eb-9689-5085d1092dfe.png)
> 修改密码出现了错误

https://github.com/openBI-kwc/openBI/commit/42b55c087e07cc1fc98a9f7f40e3b4e14806b5e1

**Comment by lty628** [comment]
@QQ1044 https://github.com/openBI-kwc/openBI/commit/42b55c087e07cc1fc98a9f7f40e3b4e14806b5e1 按照这个方式修改，或者更新1.0.2

**Comment by Ghost-Cavendish** [comment]
宝塔面板一键部署的还是不能登录，忘解决
![截屏2021-03-10 11 17 51](https://user-images.githubusercontent.com/56330712/110571381-726ebb80-8192-11eb-8166-13c230c163e4.png)
![截屏2021-03-10 11 18 38](https://user-images.githubusercontent.com/56330712/110571392-74d11580-8192-11eb-9a3e-65bf22374ce9.png)

**Comment by lty628** [comment]
@jk110 是否使用的apache?建议使用nginx

**Comment by jk110** [comment]
> @jk110 是否使用的apache?建议使用nginx

**Comment by Ghost-Cavendish** [comment]
![截屏2021-03-10 11 23 44](https://user-images.githubusercontent.com/56330712/110571932-67685b00-8193-11eb-96d2-4466a1eb6da0.png)
用的就是nginx

**Comment by lty628** [comment]
@jk110 刚刚宝塔安装并没有发现此问题,您可以部署将连接发出来看看吗？
