### ISSUE TITLE
安装好之后登陆提示500

### ISSUE THREAD

**Issue by NNBBXX** [openBI-kwc/openBI#11]
Server Error Code 500
数据库正常导入，
文件配置也对的
需要解禁丢函数也解禁了

**Comment by myrust-go** [comment]
可以打开报错提示吗？

同时把各种配置，也发出来看一下吧。

如果方便的话，我们可以远程帮你看一下。

**Comment by NNBBXX** [comment]
<VirtualHost *:80>
    ServerAdmin webmaster@example.com
    DocumentRoot "/home/wwwroot/e73a19c5/public"
    ServerName e73a19c5
    ServerAlias e73a19c5.net
    
    #DENY FILES
     <Files ~ (\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)$>
       Order allow,deny
       Deny from all
    </Files>
    
    #PHP
    <FilesMatch \.php$>
            SetHandler "proxy:unix:/tmp/php-cgi-72.sock|fcgi://localhost"
    </FilesMatch>
    
    #PATH
    <Directory "/home/wwwroot/e73a19c5/public">
        SetOutputFilter DEFLATE
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html index.htm default.php default.html default.htm
    </Directory>
</VirtualHost>

**Comment by myrust-go** [comment]
我们对apache 的支持测试比较少，可否换成nginx 进行运行？

**Comment by NNBBXX** [comment]
disable_functions = passthru,exec,system,putenv,chroot,chgrp,chown,shell_exec,proc_open,pcntl_exec,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,imap_open,apache_setenv

**Comment by NNBBXX** [comment]
服务器里都是apache在运营，有些对Nginx支持不好  不太好切换

**Comment by NNBBXX** [comment]
php是7.2

**Comment by NNBBXX** [comment]
apache没法用这个系统吗？

**Comment by myrust-go** [comment]
> apache没法用这个系统吗？

是可以的，不过我们在上面做的测试很少。

得想办法调试和测试才能解决。

**Comment by NNBBXX** [comment]
POST /user/user/doLogin 500 (Internal Server Error)
服务器是宝塔安装的环境

**Comment by NNBBXX** [comment]
你可以教我吗？我想自己试一试

**Comment by NNBBXX** [comment]
打开了php报错详细日志。报错文件是base.php。putenv函数的位置，是被php禁用了。移除后能正常登陆了。
