### ISSUE TITLE
宝塔面板部署登录报500

### ISSUE THREAD

**Issue by Ghost-Cavendish** [openBI-kwc/openBI#3]
![截屏2021-03-10 11 23 44](https://user-images.githubusercontent.com/56330712/110572085-b3b39b00-8193-11eb-9a54-32880eb31763.png)
用的就是nginx

**Comment by Ghost-Cavendish** [comment]
http://test.ghost-jack.top/openv/#/login

**Comment by lty628** [comment]
![image](https://user-images.githubusercontent.com/24287914/110574104-6f29fe80-8197-11eb-879d-17b32dfef5a2.png)
删除putenv （允许此函数）重启php-fpm 即可

**Comment by crazyYG** [comment]
宝塔禁用了   putenv 函数

**Comment by Ghost-Cavendish** [comment]
谢谢
