### ISSUE TITLE
求助部署后登陆404

### ISSUE THREAD

**Issue by zxxfire** [openBI-kwc/openBI#4]
登陆请求404，也没找到路由设置的地方
![image](https://user-images.githubusercontent.com/2087318/110586131-a5be4400-81ac-11eb-9129-e86700229a3b.png)

**Comment by lty628** [comment]
@zxxfire 自行部署后请将重写规则加入nginx配置中相应的server模块
`location / {  if (!-e $request_filename) { rewrite ^(.*)$ /index.php?s=/$1 last; break; } }`
参考文档：[https://www.kancloud.cn/manual/thinkphp5/177576](https://www.kancloud.cn/manual/thinkphp5/177576)
