### ISSUE TITLE
登录提示“警告  Server Error Code 500”

### ISSUE THREAD

**Issue by ulysses936** [openBI-kwc/openBI#6]
用的宝塔一键部署，不管是使用默认密码登陆还是随便输入一个密码都提示“警告  Server Error Code 500”
![图片](https://user-images.githubusercontent.com/55591249/110884613-53059900-8320-11eb-9806-8367a26b5b41.png)

**Comment by ulysses936** [comment]
版本的话默认部署的是1.01版本 然后我下了1.02的release替换了 还是这个情况

**Comment by ulysses936** [comment]
我知道了，一键部署的时候提示要解禁fileinfo,popen,putenv函数，我以为是自动解禁的，实际上要手动解禁orz

**Comment by lty628** [comment]
@ulysses936 是的，1.0.2的宝塔安装 putenv的问题已添加到解禁列表中了
